### ISSUE TITLE
Unhandled Promise Rejection TypeError: Setting a value of type `undefined` for key `rates` is not allowed as it's not supported by JSON

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [sarthology/caligator#97]
I get the following error on startup:
Unhandled Promise Rejection
TypeError: Setting a value of type `undefined` for key `rates` is not allowed as it's not supported by JSON
    at checkValueType (C:/Users/{myUser}/AppData/Local/Programs/caligator/resources/app.asar/node_modules/conf/index.js:32:9)
    at set (C:/Users/{myUser}/AppData/Local/Programs/caligator/resources/app.asar/node_modules/conf/index.js:135:4)
    at ElectronStore.set (C:/Users/{myUser}/AppData/Local/Programs/caligator/resources/app.asar/node_modules/conf/index.js:146:5)
    at cacheRates (C:/Users/{myUser}/AppData/Local/Programs/caligator/resources/app.asar/utils/cacheRates.js:33:11)
I substituted my username with {myUser}

**Comment by JovialMockingbird** [comment]
Run as admin is a temporary workaround

**Comment by bryangateley** [comment]
Edition	Windows 11 Home
Version	21H2
OS build	22000.1098
Experience	Windows Feature Experience Pack 1000.22000.1098.0

Run as admin does not work for me

**Comment by jesusmoreno1980** [comment]
same issue WINDOWS 11 pro .... 23H2 OS build 22631.2191

Run as admin does not work for me also
